[build]
builder = "nixpacks"

[deploy]
buildCommand = "npm run build"
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "quiz" 